/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "imgfinal.v:2" *)
module state_flow(clk, reset, start, done, data_signal);
  (* src = "imgfinal.v:12" *)
  wire _00_;
  (* src = "imgfinal.v:12" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "imgfinal.v:4" *)
  input clk;
  (* onehot = 32'd1 *)
  wire [2:0] current_state;
  (* src = "imgfinal.v:9" *)
  output data_signal;
  (* src = "imgfinal.v:3" *)
  input done;
  (* src = "imgfinal.v:5" *)
  input reset;
  (* src = "imgfinal.v:6" *)
  input start;
  (* src = "imgfinal.v:8" *)
  wire start_proc;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:46" *)
  LUT4 #(
    .INIT(16'haccc)
  ) _06_ (
    .I0(current_state[1]),
    .I1(current_state[0]),
    .I2(start_proc),
    .I3(start),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd2297491696)
  ) _07_ (
    .I0(current_state[2]),
    .I1(done),
    .I2(current_state[1]),
    .I3(start_proc),
    .I4(start),
    .O(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:51" *)
  LUT5 #(
    .INIT(32'd3221200896)
  ) _08_ (
    .I0(current_state[0]),
    .I1(done),
    .I2(start_proc),
    .I3(start),
    .I4(current_state[2]),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h80)
  ) _09_ (
    .I0(current_state[2]),
    .I1(start_proc),
    .I2(start),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:42" *)
  LUT3 #(
    .INIT(8'h7f)
  ) _10_ (
    .I0(start_proc),
    .I1(current_state[1]),
    .I2(reset),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/lut_map.v:34" *)
  LUT1 #(
    .INIT(2'h1)
  ) _11_ (
    .I0(done),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _12_ (
    .C(clk),
    .CE(1'h1),
    .D(_03_),
    .Q(current_state[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _13_ (
    .C(clk),
    .CE(1'h1),
    .D(_04_),
    .Q(current_state[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:26" *)
  FDRE #(
    .INIT(1'h0)
  ) _14_ (
    .C(clk),
    .CE(1'h1),
    .D(_05_),
    .Q(current_state[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _15_ (
    .C(clk),
    .CE(_02_),
    .D(_00_),
    .Q(data_signal),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/xilinx/ff_map.v:29" *)
  FDRE #(
    .INIT(1'h0)
  ) _16_ (
    .C(clk),
    .CE(start),
    .D(_01_),
    .Q(start_proc),
    .R(1'h0)
  );
endmodule
